### ISSUE TITLE
Error when I type the password correctly.

### ISSUE THREAD

**Issue by Rongyu68** [nileshprasad137/keystroke-dynamics-datagen#3]
~/keystroke-dynamics-datagen$ python3 record_keystroke.py
Enter your name: alex_rep1
enter 2 times more!
Enter '.tie5Roanl' : .tie5Roanl
pwd correct!
Traceback (most recent call last):
  File "record_keystroke.py", line 99, in <module>
    key_timings[key.lower()]["keyDown"] - key_timings[key]["keyUp"]
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "record_keystroke.py", line 102, in <module>
    key_timings[key]["keyDown"] - key_timings[key]["keyUp"]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

Could you please tell me how to debug with that?

**Comment by nileshprasad137** [comment]
can you try again and let me know, script will work on linux and macos.
